Repository flagbit/category-bundle, pull requests merged in 2022-02, with the labels that each got.

#5 Add github and codecov badges to readme
  README.md
Labels: size/XS

#4 Fix of coverage path in frontend-tests workflow
  .github/workflows/frontend-tests.yml
Labels: size/XS

#2 Visual response on config save
  src/Resources/public/js/property/config-form.tsx
Labels: size/M

#3 Redesign of the category properties config
  src/Resources/public/js/property/type-config/base.tsx
  src/Resources/public/js/property/type-config/config-renderer.tsx
  src/Resources/public/js/property/type-config/new-config.tsx
  src/Resources/public/less/index.less
Labels: size/S

#8 Minor bugfixes and adding an error message
  jest.config.js
  jest/public/js/property/type-config/new-config.test.tsx
  src/Resources/public/js/property/config-form.tsx
  src/Resources/public/js/property/property-form.tsx
  src/Resources/public/js/property/type-config/new-config.tsx
  src/Resources/translations/jsmessages.de.xlf
  src/Resources/translations/jsmessages.en.xlf
Labels: size/S

#10 Ignore PHPLint files
  .gitignore
Labels: enhancement, size/XS

#9 Introduce backend integration testing
  phpcs.xml.dist
  phpunit.xml.dist
  tests/Extension/AkeneoFileStructureExtension.php
  tests/OverriddenServices/ExportTest.php
  tests/OverriddenServices/SerializerTest.php
  tests/TestKernel.php
  tests/config/bundles.php
  tests/config/packages/test/imports.yml
  tests/config/packages/test/oneup_flysystem.yml
Labels: size/L

#7 Introduce Json schema checks
  composer.json
  spec/Flagbit/Bundle/CategoryBundle/Controller/InternalApi/CategoryConfigControllerSpec.php
  spec/Flagbit/Bundle/CategoryBundle/EventListener/SavePropertyListenerSpec.php
  spec/Flagbit/Bundle/CategoryBundle/Schema/SchemaValidatorSpec.php
  src/Controller/InternalApi/CategoryConfigController.php
  src/EventListener/SavePropertyListener.php
  src/Exception/Exception.php
  src/Exception/InvalidFile.php
  src/Exception/ValidationFailed.php
  src/Resources/config/schema/config.json
  src/Resources/config/schema/property.json
  src/Resources/config/services.yml
  src/Schema/SchemaValidator.php
Labels: size/XL

#6 Implement category property import
  spec/Flagbit/Bundle/CategoryBundle/Connector/ArrayConverter/FlatToStandard/CategoryDecoratorSpec.php
  spec/Flagbit/Bundle/CategoryBundle/Entity/CategoryPropertySpec.php
  spec/Flagbit/Bundle/CategoryBundle/EventListener/BulkSavePropertyListenerSpec.php
  src/Connector/ArrayConverter/FlatToStandard/CategoryDecorator.php
  src/Entity/CategoryProperty.php
  src/EventListener/BulkSavePropertyListener.php
  src/Resources/config/services.yml
Labels: enhancement, size/XL
